In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df_wiki = pd.read_csv('/content/drive/MyDrive/wikidata.csv')
df_dbp = pd.read_csv('/content/drive/MyDrive/wikidata.csv')

# Lihat 5 data teratas
print("=== Wikidata ===")
display(df_wiki)

print("=== DBpedia ===")
display(df_dbp)

=== Wikidata ===

,qid,penyakitLabel,gejalaLabel,obatLabel,kategoriLabel,treatmentLabel
0,Q1432717,catatonic schizophrenia,waxy flexibility,NaN,schizophrenia,NaN
1,Q1432717,catatonic schizophrenia,muteness,NaN,schizophrenia,NaN
2,Q1432717,catatonic schizophrenia,catalepsy,NaN,schizophrenia,NaN
3,Q1432717,catatonic schizophrenia,negativism,NaN,schizophrenia,NaN
4,Q1432717,catatonic schizophrenia,Pavlov's symptom,NaN,schizophrenia,NaN
...,...,...,...,...,...,...
19626,Q16333787,Wuchereria bancrofti filariasis,lymphedema,NaN,nematode infection,NaN
19627,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,genetic disease,NaN
19628,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,intestinal pseudo-obstruction,NaN
19629,Q18199350,Faroe SUCLA2 related disease,deafness,NaN,genetic disease,NaN
19630,Q18199350,Faroe SUCLA2 related disease,muscle weakness,NaN,genetic disease,NaN

=== DBpedia ===

,qid,penyakitLabel,gejalaLabel,obatLabel,kategoriLabel,treatmentLabel
0,Q1432717,catatonic schizophrenia,waxy flexibility,NaN,schizophrenia,NaN
1,Q1432717,catatonic schizophrenia,muteness,NaN,schizophrenia,NaN
2,Q1432717,catatonic schizophrenia,catalepsy,NaN,schizophrenia,NaN
3,Q1432717,catatonic schizophrenia,negativism,NaN,schizophrenia,NaN
4,Q1432717,catatonic schizophrenia,Pavlov's symptom,NaN,schizophrenia,NaN
...,...,...,...,...,...,...
19626,Q16333787,Wuchereria bancrofti filariasis,lymphedema,NaN,nematode infection,NaN
19627,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,genetic disease,NaN
19628,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,intestinal pseudo-obstruction,NaN
19629,Q18199350,Faroe SUCLA2 related disease,deafness,NaN,genetic disease,NaN
19630,Q18199350,Faroe SUCLA2 related disease,muscle weakness,NaN,genetic disease,NaN

In [3]:
df_wiki.columns

Index(['qid', 'penyakitLabel', 'gejalaLabel', 'obatLabel', 'kategoriLabel',
       'treatmentLabel'],
      dtype='object')

In [4]:
df_dbp.columns

Index(['qid', 'penyakitLabel', 'gejalaLabel', 'obatLabel', 'kategoriLabel',
       'treatmentLabel'],
      dtype='object')

In [26]:
# Clean the 'penyakitLabel' and 'label' columns by stripping spaces and converting to lowercase
df_wiki['qid'] = df_wiki['qid'].str.strip().str.lower()
df_dbp['qid'] = df_dbp['qid'].str.strip().str.lower()

# Merge the dataframes based on cleaned columns
merged_df = pd.merge(df_wiki, df_dbp, left_on='qid', right_on='qid', how='left')

# Show the merged result
merged_df

,qid,penyakitLabel_x,gejalaLabel_x,obatLabel,kategoriLabel_x,treatmentLabel_x,penyakitDBpedia,penyakitLabel_y,wikidataEntity,gejalaLabel_y,treatmentLabel_y,kategoriLabel_y
0,q1432717,catatonic schizophrenia,waxy flexibility,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,q1432717,catatonic schizophrenia,muteness,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,q1432717,catatonic schizophrenia,catalepsy,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,q1432717,catatonic schizophrenia,negativism,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,q1432717,catatonic schizophrenia,Pavlov's symptom,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
31648,q16333787,Wuchereria bancrofti filariasis,lymphedema,NaN,nematode infection,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31649,q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31650,q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,intestinal pseudo-obstruction,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31651,q18199350,Faroe SUCLA2 related disease,deafness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31652,q18199350,Faroe SUCLA2 related disease,muscle weakness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import pandas as pd

# Assuming df_wiki and df_dbp are already loaded DataFrames

# Perform an inner join on the 'qid' column to get rows with the same qid in both dataframes
df_matching_qid = pd.merge(df_wiki, df_dbp, on='qid', how='left')

# Show the resulting DataFrame with matching qid
df_matching_qid

,qid,penyakitLabel_x,gejalaLabel_x,obatLabel,kategoriLabel_x,treatmentLabel_x,penyakitDBpedia,penyakitLabel_y,wikidataEntity,gejalaLabel_y,treatmentLabel_y,kategoriLabel_y
0,Q1432717,catatonic schizophrenia,waxy flexibility,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Q1432717,catatonic schizophrenia,muteness,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Q1432717,catatonic schizophrenia,catalepsy,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q1432717,catatonic schizophrenia,negativism,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q1432717,catatonic schizophrenia,Pavlov's symptom,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
31648,Q16333787,Wuchereria bancrofti filariasis,lymphedema,NaN,nematode infection,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31649,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31650,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,intestinal pseudo-obstruction,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31651,Q18199350,Faroe SUCLA2 related disease,deafness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31652,Q18199350,Faroe SUCLA2 related disease,muscle weakness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Melakukan merge antara df_wiki dan df_dbp berdasarkan qid
df_merged = pd.merge(df_wiki, df_dbp, on='qid', how='left', suffixes=('_wiki', '_dbp'))

# Menampilkan hasil merge
df_merged

,qid,penyakitLabel_wiki,gejalaLabel_wiki,obatLabel,kategoriLabel_wiki,treatmentLabel_wiki,penyakitDBpedia,penyakitLabel_dbp,wikidataEntity,gejalaLabel_dbp,treatmentLabel_dbp,kategoriLabel_dbp
0,Q1432717,catatonic schizophrenia,waxy flexibility,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Q1432717,catatonic schizophrenia,muteness,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Q1432717,catatonic schizophrenia,catalepsy,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Q1432717,catatonic schizophrenia,negativism,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Q1432717,catatonic schizophrenia,Pavlov's symptom,NaN,schizophrenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
31648,Q16333787,Wuchereria bancrofti filariasis,lymphedema,NaN,nematode infection,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31649,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31650,Q17119515,Mungan syndrome,chronic intestinal pseudoobstruction,NaN,intestinal pseudo-obstruction,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31651,Q18199350,Faroe SUCLA2 related disease,deafness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31652,Q18199350,Faroe SUCLA2 related disease,muscle weakness,NaN,genetic disease,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_dbp.notna().sum()

penyakitDBpedia    10000
qid                10000
penyakitLabel      10000
wikidataEntity     10000
gejalaLabel         3821
treatmentLabel      2781
kategoriLabel       9984
dtype: int64

In [5]:
df_matching_qid.notna().sum()

qid                 31653
penyakitLabel_x     31653
gejalaLabel_x       31653
obatLabel           31078
kategoriLabel_x     31565
treatmentLabel_x    31078
penyakitDBpedia     12198
penyakitLabel_y     12198
wikidataEntity      12198
gejalaLabel_y       11550
treatmentLabel_y        0
kategoriLabel_y     12198
dtype: int64

In [23]:
# Gabungkan kolom yang berakhiran _x dan _y menjadi satu kolom saja
df_matching_qid['penyakitLabel'] = df_matching_qid['penyakitLabel_x'].combine_first(df_matching_qid['penyakitLabel_y'])
df_matching_qid['gejalaLabel'] = df_matching_qid['gejalaLabel_x'].combine_first(df_matching_qid['gejalaLabel_y'])
df_matching_qid['kategoriLabel'] = df_matching_qid['kategoriLabel_x'].combine_first(df_matching_qid['kategoriLabel_y'])
df_matching_qid['treatmentLabel'] = df_matching_qid['treatmentLabel_x'].combine_first(df_matching_qid['treatmentLabel_y'])

# Menghapus kolom _x dan _y yang sudah digabung
df_matching_qid.drop(['penyakitLabel_x', 'penyakitLabel_y', 'gejalaLabel_x', 'gejalaLabel_y',
                        'kategoriLabel_x', 'kategoriLabel_y', 'treatmentLabel_x',
                       'treatmentLabel_y'], axis=1, inplace=True)

# Menampilkan hasil setelah penggabungan kolom
df_matching_qid

,qid,obatLabel,penyakitDBpedia,wikidataEntity,penyakitLabel,gejalaLabel,kategoriLabel,treatmentLabel
0,Q1432717,NaN,NaN,NaN,catatonic schizophrenia,waxy flexibility,schizophrenia,NaN
1,Q1432717,NaN,NaN,NaN,catatonic schizophrenia,muteness,schizophrenia,NaN
2,Q1432717,NaN,NaN,NaN,catatonic schizophrenia,catalepsy,schizophrenia,NaN
3,Q1432717,NaN,NaN,NaN,catatonic schizophrenia,negativism,schizophrenia,NaN
4,Q1432717,NaN,NaN,NaN,catatonic schizophrenia,Pavlov's symptom,schizophrenia,NaN
...,...,...,...,...,...,...,...,...
31648,Q16333787,NaN,NaN,NaN,Wuchereria bancrofti filariasis,lymphedema,nematode infection,NaN
31649,Q17119515,NaN,NaN,NaN,Mungan syndrome,chronic intestinal pseudoobstruction,genetic disease,NaN
31650,Q17119515,NaN,NaN,NaN,Mungan syndrome,chronic intestinal pseudoobstruction,intestinal pseudo-obstruction,NaN
31651,Q18199350,NaN,NaN,NaN,Faroe SUCLA2 related disease,deafness,genetic disease,NaN
31652,Q18199350,NaN,NaN,NaN,Faroe SUCLA2 related disease,muscle weakness,genetic disease,NaN

In [25]:
import os

# Save the filtered DataFrame to a CSV file
df_matching_qid.to_csv('/content/df_final.csv', index=False)